#!/bin/sh

# network
/sbin/ifconfig lo up

/bin/mount -t proc none /proc
/bin/mount -t sysfs none /sys

/bin/cat << "EOF"
  _______ .______          ___   ____    ____  ____     ___      __
 /  _____||   _  \        /   \  \   \  /   / |___ \   / _ \    / /
|  |  __  |  |_)  |      /  ^  \  \   \/   /    __) | | (_) |  / /_
|  | |_ | |      /      /  /_\  \  \_    _/    |__ <   > _ <  | '_ \
|  |__| | |  |\  \----./  _____  \   |  |      ___) | | (_) | | (_) |
 \______| | _| `._____/__/     \__\  |__|     |____/   \___/   \___/
Linux for i386 machines
EOF

/bin/mount /dev/sda2 /mnt

exit 0
